# Preprocessing Data Analyst Job Postings [Pay, Skills, Benefits] Folder

In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import gdown

In [8]:
id = '1cHM6IvoayUw8wtIiquraGavdw3J6pqnM'
output = 'data_analyst_job_posting.csv'

if not os.path.exists(output):
    print("Download Dataset.....")
    gdown.download(f'https://drive.google.com/uc?id={id}',
                  output,
                  quiet=False # keterangan saat download
                  )
else:
    print("Dataset already exists")

Download Dataset.....

Downloading...
From (original): https://drive.google.com/uc?id=1cHM6IvoayUw8wtIiquraGavdw3J6pqnM
From (redirected): https://drive.google.com/uc?id=1cHM6IvoayUw8wtIiquraGavdw3J6pqnM&confirm=t&uuid=84657651-cdd5-44a1-be03-e1280d76e074
To: /home/alvin/Documents/Capstone-Project-Dicoding/Preprocessing data/data_analyst_job_posting.csv
100%|█████████████████████████████████████████| 290M/290M [11:51<00:00, 407kB/s]

In [32]:
df = pd.read_csv('./data_analyst_job_posting.csv')
df.head()

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,...,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
0,0,0,Data Analyst,Meta,Anywhere,via LinkedIn,In the intersection of compliance and analytic...,"['15 hours ago', '101K–143K a year', 'Work fro...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,101K–143K,a year,122000.0,101000.0,143000.0,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']"
1,1,1,Data Analyst,ATC,United States,via LinkedIn,Job Title: Entry Level Business Analyst / Prod...,"['12 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,2,2,Aeronautical Data Analyst,"Garmin International, Inc.","Olathe, KS",via Indeed,Overview:\n\nWe are seeking a full-time...\nAe...,"['18 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbm...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql']
3,3,3,Data Analyst - Consumer Goods - Contract to Hire,Upwork,Anywhere,via Upwork,Enthusiastic Data Analyst for processing sales...,"['12 hours ago', '15–25 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW...,NaN,...,NaN,15–25,an hour,20.0,15.0,25.0,20.0,NaN,41600.0,"['powerpoint', 'excel', 'power_bi']"
4,4,4,Data Analyst | Workforce Management,Krispy Kreme,United States,via LinkedIn,Overview of Position\n\nThis position will be ...,"['7 hours ago', '90K–110K a year', 'Contractor']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,90K–110K,a year,100000.0,90000.0,110000.0,NaN,100000.0,100000.0,"['powerpoint', 'excel', 'outlook', 'word']"

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61953 entries, 0 to 61952
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           61953 non-null  int64
 1   index                61953 non-null  int64
 2   title                61953 non-null  object
 3   company_name         61953 non-null  object
 4   location             61916 non-null  object
 5   via                  61944 non-null  object
 6   description          61953 non-null  object
 7   extensions           61953 non-null  object
 8   job_id               61953 non-null  object
 9   thumbnail            38194 non-null  object
 10  posted_at            61763 non-null  object
 11  schedule_type        61707 non-null  object
 12  work_from_home       27980 non-null  object
 13  salary               10088 non-null  object
 14  search_term          61953 non-null  object
 15  date_time            61953 non-null  object
 16  search_location      61953 non-null  object
 17  commute_time         0 non-null      float64
 18  salary_pay           10088 non-null  object
 19  salary_rate          10088 non-null  object
 20  salary_avg           10088 non-null  float64
 21  salary_min           9512 non-null   float64
 22  salary_max           9512 non-null   float64
 23  salary_hourly        5900 non-null   float64
 24  salary_yearly        4069 non-null   float64
 25  salary_standardized  10088 non-null  float64
 26  description_tokens   61953 non-null  object
dtypes: float64(7), int64(2), object(18)
memory usage: 12.8+ MB

In [34]:
df = df[['title', 'description', 'description_tokens']].copy()
df.head()

,title,description,description_tokens
0,Data Analyst,In the intersection of compliance and analytic...,"['tableau', 'r', 'python', 'sql']"
1,Data Analyst,Job Title: Entry Level Business Analyst / Prod...,[]
2,Aeronautical Data Analyst,Overview:\n\nWe are seeking a full-time...\nAe...,['sql']
3,Data Analyst - Consumer Goods - Contract to Hire,Enthusiastic Data Analyst for processing sales...,"['powerpoint', 'excel', 'power_bi']"
4,Data Analyst | Workforce Management,Overview of Position\n\nThis position will be ...,"['powerpoint', 'excel', 'outlook', 'word']"

In [35]:
df['title'].unique()

array(['Data Analyst', 'Aeronautical Data Analyst',
       'Data Analyst - Consumer Goods - Contract to Hire', ...,
       'Data Analyst - Business Intelligence',
       'COOP - Senior Data Analyst', 'Lead FP&A Analyst- Remote, US'],
      dtype=object)

In [36]:
target_roles = ['data analyst', 'senior data analyst']

df = df[
    df['title']
    .str.strip()
    .str.lower()
    .isin(target_roles)
].copy()
df

,title,description,description_tokens
0,Data Analyst,In the intersection of compliance and analytic...,"['tableau', 'r', 'python', 'sql']"
1,Data Analyst,Job Title: Entry Level Business Analyst / Prod...,[]
5,Data Analyst,Your Job\n\nFlint Hills Resources is seeking a...,"['power_bi', 'aws', 'excel', 'sql', 'mysql', '..."
7,Data Analyst,"In order to be considered for this role, after...","['power_bi', 'tableau', 'jira', 'snowflake', '..."
9,Data Analyst,Job Summary: The Data Analyst oversees data pr...,"['r', 'python']"
...,...,...,...
61883,Data Analyst,Job Description:\n\nWe are seeking a Data Anal...,[]
61895,Senior Data Analyst,Job Description\n\nProvides programs to improv...,"['t-sql', 'power_bi', 'tableau', 'sharepoint',..."
61922,Data Analyst,• InTulsa is partnering with Tulsa Remote to f...,"['bigquery', 'excel', 'javascript', 'power_bi'..."
61942,Data Analyst,What you will do:\n• Build reporting dashboard...,"['tableau', 'sql']"
61943,Data Analyst,• InTulsa is partnering with Tulsa Remote to f...,"['bigquery', 'excel', 'javascript', 'power_bi'..."

In [37]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6055 entries, 0 to 61942
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               6055 non-null   object
 1   description         6055 non-null   object
 2   description_tokens  6055 non-null   object
dtypes: object(3)
memory usage: 189.2+ KB

In [40]:
# Role Normalization

def map_role(title):
    title = title.lower()
    
    if 'data analyst' in title:
        return 'data analyst'
    elif 'frontend' in title or 'front end' in title or 'react' in title or 'front-end' in title:
        return 'frontend'
    elif "backend" in title or 'back end' in title or "node" in title or 'back-end' in title:
        return "backend"
    else:
        return None
df['role'] = df['title'].apply(map_role)
df = df[df['role'].notnull()].copy()
df

,title,description,description_tokens,role
0,Data Analyst,In the intersection of compliance and analytic...,"['tableau', 'r', 'python', 'sql']",data analyst
1,Data Analyst,Job Title: Entry Level Business Analyst / Prod...,[],data analyst
5,Data Analyst,Your Job\n\nFlint Hills Resources is seeking a...,"['power_bi', 'aws', 'excel', 'sql', 'mysql', '...",data analyst
7,Data Analyst,"In order to be considered for this role, after...","['power_bi', 'tableau', 'jira', 'snowflake', '...",data analyst
9,Data Analyst,Job Summary: The Data Analyst oversees data pr...,"['r', 'python']",data analyst
...,...,...,...,...
61729,Data Analyst,"Our client, a leader in the Data Industry, is ...","['excel', 'sql']",data analyst
61822,Senior Data Analyst,"Tickets For Less®, a leading live entertainmen...","['github', 'qlik', 'tableau', 'power_bi', 'bit...",data analyst
61846,Data Analyst,Data Analyst Job Description Daniel's Restaura...,[],data analyst
61895,Senior Data Analyst,Job Description\n\nProvides programs to improv...,"['t-sql', 'power_bi', 'tableau', 'sharepoint',...",data analyst
61942,Data Analyst,What you will do:\n• Build reporting dashboard...,"['tableau', 'sql']",data analyst

In [41]:
import re

def casefolding(text):
    return text.lower()

def cleaning(text):
    text = re.sub(r"http\S+", "", text)
    
    text = text.replace('\n', ' ')
    text = text.replace('*','')
    
    text = text.strip()
    
    text = re.sub(r'\s+', ' ', text)
    
    return text

for col in df.columns:
    df.loc[:, f"clean_{col}"] = df[col].apply(casefolding)
    df.loc[:, f"clean_{col}"] = df[f"clean_{col}"].apply(cleaning)
df

,title,description,description_tokens,role,clean_title,clean_description,clean_description_tokens,clean_role
0,Data Analyst,In the intersection of compliance and analytic...,"['tableau', 'r', 'python', 'sql']",data analyst,data analyst,in the intersection of compliance and analytic...,"['tableau', 'r', 'python', 'sql']",data analyst
1,Data Analyst,Job Title: Entry Level Business Analyst / Prod...,[],data analyst,data analyst,job title: entry level business analyst / prod...,[],data analyst
5,Data Analyst,Your Job\n\nFlint Hills Resources is seeking a...,"['power_bi', 'aws', 'excel', 'sql', 'mysql', '...",data analyst,data analyst,your job flint hills resources is seeking a da...,"['power_bi', 'aws', 'excel', 'sql', 'mysql', '...",data analyst
7,Data Analyst,"In order to be considered for this role, after...","['power_bi', 'tableau', 'jira', 'snowflake', '...",data analyst,data analyst,"in order to be considered for this role, after...","['power_bi', 'tableau', 'jira', 'snowflake', '...",data analyst
9,Data Analyst,Job Summary: The Data Analyst oversees data pr...,"['r', 'python']",data analyst,data analyst,job summary: the data analyst oversees data pr...,"['r', 'python']",data analyst
...,...,...,...,...,...,...,...,...
61729,Data Analyst,"Our client, a leader in the Data Industry, is ...","['excel', 'sql']",data analyst,data analyst,"our client, a leader in the data industry, is ...","['excel', 'sql']",data analyst
61822,Senior Data Analyst,"Tickets For Less®, a leading live entertainmen...","['github', 'qlik', 'tableau', 'power_bi', 'bit...",data analyst,senior data analyst,"tickets for less®, a leading live entertainmen...","['github', 'qlik', 'tableau', 'power_bi', 'bit...",data analyst
61846,Data Analyst,Data Analyst Job Description Daniel's Restaura...,[],data analyst,data analyst,data analyst job description daniel's restaura...,[],data analyst
61895,Senior Data Analyst,Job Description\n\nProvides programs to improv...,"['t-sql', 'power_bi', 'tableau', 'sharepoint',...",data analyst,senior data analyst,job description provides programs to improve o...,"['t-sql', 'power_bi', 'tableau', 'sharepoint',...",data analyst
61942,Data Analyst,What you will do:\n• Build reporting dashboard...,"['tableau', 'sql']",data analyst,data analyst,what you will do: • build reporting dashboards...,"['tableau', 'sql']",data analyst

In [42]:
df['role'].value_counts()

role
data analyst    6055
Name: count, dtype: int64