# Preprocessing NxtGenIntern Folder

In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
id = '1CbA-_VFqn4NsYQShEWBJvk8AS226eTWt'
url = f'https://drive.google.com/uc?id={id}'
df = pd.read_csv(url)
df.head()

,Job Title,Job Description,Skills,Certifications
0,Admin Big Data,Responsible for managing and overseeing big da...,"Hadoop, Spark, MapReduce, Data Lakes, Data War...","Cloudera Certified Professional (CCP), Hortonw..."
1,Ansible Operations Engineer,Focuses on automating IT processes using Ansib...,"Ansible, Linux, Automation, Cloud Platforms, C...",Red Hat Certified Specialist in Ansible Automa...
2,Artifactory Administrator,Manages the Artifactory repository for build a...,"Artifactory, CI/CD, Jenkins, Docker, Maven, Gr...","JFrog Artifactory Certification, DevOps Instit..."
3,Artificial intelligence / Machine Learning Eng...,No description available,NaN,NaN
4,Artificial Intelligence / Machine Learning Leader,"Leads AI/ML projects and teams, defining strat...","AI Strategy, Machine Learning, Team Management...","AI-900: Microsoft Azure AI Fundamentals, Certi..."

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Job Title        207 non-null    object
 1   Job Description  207 non-null    object
 2   Skills           205 non-null    object
 3   Certifications   157 non-null    object
dtypes: object(4)
memory usage: 6.6+ KB

In [14]:
df.drop(columns=['Certifications'], inplace=True)
df.head()

,Job Title,Job Description,Skills
0,Admin Big Data,Responsible for managing and overseeing big da...,"Hadoop, Spark, MapReduce, Data Lakes, Data War..."
1,Ansible Operations Engineer,Focuses on automating IT processes using Ansib...,"Ansible, Linux, Automation, Cloud Platforms, C..."
2,Artifactory Administrator,Manages the Artifactory repository for build a...,"Artifactory, CI/CD, Jenkins, Docker, Maven, Gr..."
3,Artificial intelligence / Machine Learning Eng...,No description available,NaN
4,Artificial Intelligence / Machine Learning Leader,"Leads AI/ML projects and teams, defining strat...","AI Strategy, Machine Learning, Team Management..."

In [15]:
# Proses data null + duplicate

df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 198 entries, 0 to 206
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Job Title        198 non-null    object
 1   Job Description  198 non-null    object
 2   Skills           198 non-null    object
dtypes: object(3)
memory usage: 6.2+ KB

In [16]:
# Role Normalization

def map_role(title):
    title = title.lower()
    
    if 'data analyst' in title:
        return 'data analyst'
    elif 'frontend' in title or 'front end' in title or 'react' in title or 'front-end' in title:
        return 'frontend'
    elif "backend" in title or 'back end' in title or "node" in title or 'back-end' in title:
        return "backend"
    else:
        return None
df['role'] = df['Job Title'].apply(map_role)
df = df[df['role'].notnull()]
df

,Job Title,Job Description,Skills,role
14,Data Analysts,Analyzes datasets to provide actionable insigh...,"SQL, Excel, Data Visualization, Power BI, Pyth...",data analyst
72,DATA ANALYST,Analyzes data sets to extract insights that in...,"SQL, Excel, Data Visualization, Power BI, Pyth...",data analyst
99,Front End Developer,Designs and develops user-facing features for ...,"JavaScript, HTML, CSS, React, Angular, Vue.js,...",frontend
100,Front End Web Developer,Creates and maintains the visual components of...,"JavaScript, HTML, CSS, React, Angular, Vue.js,...",frontend
126,Junior Front End Developer,Assists in developing front-end components of ...,"JavaScript, HTML, CSS, React, Vue.js, Git, UI/...",frontend
164,React Developer,Develops user interfaces using React.js framew...,"JavaScript, React, HTML, CSS, Node.js, Redux, ...",frontend

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 14 to 164
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Job Title        6 non-null      object
 1   Job Description  6 non-null      object
 2   Skills           6 non-null      object
 3   role             6 non-null      object
dtypes: object(4)
memory usage: 240.0+ bytes

# Data Gak Guna (Sisa 6)